### ISSUE TITLE
Thoughts as using lru-cache as fallback if redis not installed?

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/cache-pug-templates#6]
Curious if you think this would be nice to add as a fallback <https://github.com/isaacs/node-lru-cache> @ForbesLindesay cc @OmgImAlexis?

**Comment by ForbesLindesay** [comment]
That's in memory, so you won't gain anything over the builtin pug cache.  As I understand it, the benefit of this library is that the cache survives server reboots.

**Comment by niftylettuce** [comment]
Ah yes you're right, my bad.  Must be tired.
