### ISSUE TITLE
eval returns undefined

### ISSUE THREAD

**Issue by levani** [ladjs/cache-pug-templates#7]
I tried to use plugin but it does not seem to work... Looking at the code on line 63 https://github.com/ladjs/cache-pug-templates/blob/master/index.js#L63 this eval call will always return undefined.

**Comment by niftylettuce** [comment]
@levani this is not a proper bug report - this code will not return `undefined`.  It returns a function since it eval's the template string (which is a function stored as a string).

**Comment by levani** [comment]
Well, I may be missing something but

`cache[__path__] = eval('function test() {}')`

would result in `cache[__path__]` being undefined and creating `test` function in global scope...

**Comment by niftylettuce** [comment]
It is `pug.cache[filename] = eval(compiledStr);`, so `pug.cache['some-file-name.pug'] = function test() {}`.

**Comment by niftylettuce** [comment]
If there's a bug here that I'm not seeing please file a pull request and I can review

**Comment by niftylettuce** [comment]
Or perhaps you could write a test case that shows it fails?

**Comment by levani** [comment]
I will try to send PR but I'm not quite sure that I'm right yet :))

In redis, functions are stored as strings like this:

```
function template(locals) {
  var pug_html = ""
  ...
  return pug_html;
}
```

than you `eval` that string and assign it to an object property. Am I right?

Can you run this in browser console and see what's the value of `o.file`?

```
let o = {};
o.file = eval('function template() { var html="test html"; return html; }')
```

**Comment by niftylettuce** [comment]
You have to wrap it with parenthesis to get desired output:

```js
const o = {};
o.file = eval('(function template() { var html="test html"; return html; })');
```

**Comment by niftylettuce** [comment]
@levani thanks for finding this core bug 👍 👏 I've gone ahead and patched it.  I've also released a new version and deprecated all prior versions.

**Comment by niftylettuce** [comment]
Please download v0.0.8+, thanks!
