### ISSUE TITLE
Not support on windows

### ISSUE THREAD

**Issue by 7iomka** [ladjs/cache-pug-templates#8]
![image](https://user-images.githubusercontent.com/18473137/52731229-4641da00-2fce-11e9-8b8a-8caebd9e21df.png)

**Comment by niftylettuce** [comment]
Please try v2.0.1+ as it now should work just fine 👍!!! 

`npm install cache-pug-templates@latest`

Thank you, also see the latest README/options at <https://github.com/ladjs/cache-pug-templates>
